# Complete example of most of cutler's pattern usage

[menuextra.clock]
FlashDateSeparators = true
DateFormat = "\"HH:mm:ss\""
Show24Hour = true
ShowAMPM = false
ShowDate = 2
ShowDayOfWeek = false
ShowSeconds = true

[finder]
AppleShowAllFiles = true
CreateDesktop = false
ShowPathbar = true
FXRemoveOldTrashItems = true

[AppleMultitouchTrackpad]
FirstClickThreshold = 0
TrackpadThreeFingerDrag = true

[dock]
tilesize = 50
autohide = true
magnification = false
orientation = "right"
mineffect = "suck"
autohide-delay = 0
autohide-time-modifier = 0.6
expose-group-apps = true

[NSGlobalDomain.com.apple.keyboard]
fnState = false

# External command execution
# This includes setting the global hostname and configuring sudo authentication with Touch ID.

[external.variables]
hostname = "darkstar"

[external]
[[external.command]]
cmd = "scutil --set ComputerName &hostname"
sudo = true

[[external.command]]
cmd = "scutil"
args = ["--set", "HostName", "$hostname"] # separated args style
sudo = true

[[external.command]]
cmd = "scutil --set LocalHostName &hostname"
sudo = true

[[external.command]]
cmd = "sed -e 's/^#auth/auth/' /etc/pam.d/sudo_local.template | sudo tee /etc/pam.d/sudo_local"
