# Remove the line below to activate this configuration.
lock = true

[set.finder]
AppleShowAllFiles = true
CreateDesktop = false
ShowPathbar = true
FXRemoveOldTrashItems = true

[set.dock]
tilesize = 46
autohide = true
orientation = "left"
mineffect = "suck"
autohide-delay = 0
autohide-time-modifier = 0.6
expose-group-apps = true

[set.NSGlobalDomain.com.apple.keyboard]
fnState = false
