name: Rust Tests (Manual Dispatch)

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "tests"
  cancel-in-progress: true

jobs:
  test:
    name: Test Suite
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # - name: Cache Rust dependencies
      #   if: steps.check_changes.outputs.changes_detected == 'true'
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/registry
      #       ~/.cargo/git
      #       target
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings
