[book]
title = "cutler Book"
author = "HitBlast"
description = "Documentation for cutler: Powerful, declarative settings management for your Mac, with speed."
multilingual = false

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
mathjax-support = false
additional-css = []
additional-js = []
copy-fonts = true
git-repository-url = "https://github.com/hitblast/cutler"
edit-url-template = "https://github.com/hitblast/cutler/edit/main/book/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30

[output.html.fold]
enable = true

[output.html.playground]
editable = false
copyable = true
line-numbers = false
runnable = false

[preprocessor.links]
# This enables automatic link checking for the book.
# Remove or comment out if not using the links preprocessor.
# optional = true

[build]
build-dir = "book-output"
create-missing = true
use-default-preprocessors = true
